sudo: required
services:
- docker
language: bash
script:
- docker build -t ybaruchel/kniot-scrapper .
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin &&
  docker tag ybaruchel/kniot-scrapper ybaruchel/kniot-scrapper:master-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER &&
  docker push ybaruchel/kniot-scrapper:master-$TRAVIS_COMMIT-$TRAVIS_BUILD_NUMBER