version: "3.1"
services:
  kniot-scrapper:
    build:
      context: .
    environment:
      XML_STORE_PATH: dumps/
    container_name: kniot-scrapper
    hostname: kniot-scrapper
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
