version: "3.1"
services:
  kniot-scrapper:
    build:
      context: ./
    container_name: kniot-scrapper
    hostname: kniot-scrapper
    volumes:
    - ./:/usr/src/app
    tty: true
    stdin_open: true